version: 1.0.{branch}.{build}

max_jobs: 2

image: Visual Studio 2015

install:
    - mkdir build
    - cd build
    - '"C:\Program Files (x86)\cmake\bin\cmake.exe" .. -G"Visual Studio 14 Win64"'

platform: x64

build:
    parallel: false
    project: build/gentlemanly_engine.sln

